filter:
    excluded_paths:
        - 'Documentation/*'
        - 'Tests/*'
        - 'Resources/JavaScript/*'
        - 'Resources/Private/Solr/*'
    paths:
        - 'Classes/*'
tools:

    php_cpd:
        enabled: true

    php_code_sniffer:
        enabled: true
        config:
            standard: TYPO3CMS

    # we do this on travis
    php_cs_fixer:
        enabled: false

    php_mess_detector:
        enabled: true
        config:
            controversial_rules:
                superglobals: false

    php_pdepend:
        enabled: true

    php_analyzer:
        enabled: true

    external_code_coverage:
        runs: 2
        timeout: 1800

build_failure_conditions:
    - 'patches.label("Doc Comments").new.count > 0'
    - 'patches.label("Spacing").new.count > 0'
    - 'issues.label("coding-style").new.count > 0'
    - 'issues.severity(>= MAJOR).new.exists'
    - 'project.metric("scrutinizer.quality", < 8)'
    - 'project.metric_change("scrutinizer.test_coverage", < -0.10)'