filter:
  excluded_paths:
    - 'Documentation/*'
    - 'Tests/*'
    - 'Resources/Public/JavaScript/*'
    - 'Resources/Private/Solr/*'
  paths:
    - 'Classes/*'

tools:
  php_cpd:
    enabled: true

  # we do this on GitHub-Actions via typo3/coding-standards
  php_code_sniffer:
    enabled: false
  # we do this on GitHub-Actions via typo3/coding-standards
  php_cs_fixer:
    enabled: false

  php_mess_detector:
    enabled: true
    config:
      controversial_rules:
        superglobals: false

  php_pdepend:
    enabled: true

  php_analyzer:
    enabled: true
    dependency_paths:
      - 'Resources/Private/Php/*'

  external_code_coverage:
    runs: 2
    timeout: 2400

checks:
  php:
    excluded_dependencies:
      - typo3/cms-install
    avoid_superglobals: false

build_failure_conditions:
  - 'patches.label("Doc Comments").count > 10'
  - 'patches.label("Spacing").count > 15'
  - 'issues.label("coding-style").count > 10'
  - 'issues.severity(>= MAJOR).count > 260'
  - 'project.metric("scrutinizer.quality", < 8)'
  - 'project.metric_change("scrutinizer.test_coverage", < -0.10)'


build:
  environment:
    php:
      # We want to test with the smallest supported TYPO3 PHP version
      version: 7.4
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
