filter:
  excluded_paths:
    - 'Documentation/*'
    - 'Tests/*'
    - 'Resources/Public/JavaScript/*'
    - 'Resources/Private/Solr/*'
  paths:
    - 'Classes/*'

tools:
  php_cpd:
    enabled: false

  # we do this on GitHub-Actions via typo3/coding-standards
  php_code_sniffer:
    enabled: false
  # we do this on GitHub-Actions via typo3/coding-standards
  php_cs_fixer:
    enabled: false

  php_mess_detector:
    enabled: false

  php_pdepend:
    enabled: false

  external_code_coverage:
    runs: 2
    timeout: 2400
