version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "solarium/solarium"
  - package-ecosystem: "composer"
      directory: "/Resources/Private/Php/ComposerLibraries"
      schedule:
        interval: "daily"
      allow:
        - dependency-name: "solarium/solarium"
