<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2009-09-15 18:31

$extensionPath = t3lib_extMgm::extPath('solr');
return array(

		// SolrPhpClient

	'apache_solr_httptransport_abstract' => $extensionPath . 'lib/SolrPhpClient/Apache/Solr/HttpTransport/Abstract.php',
	'apache_solr_httptransport_curl' => $extensionPath . 'lib/SolrPhpClient/Apache/Solr/HttpTransport/Curl.php',
	'apache_solr_httptransport_curlnoreuse' => $extensionPath . 'lib/SolrPhpClient/Apache/Solr/HttpTransport/CurlNoReuse.php',
	'apache_solr_httptransport_filegetcontents' => $extensionPath . 'lib/SolrPhpClient/Apache/Solr/HttpTransport/FileGetContents.php',
	'apache_solr_httptransport_interface' => $extensionPath . 'lib/SolrPhpClient/Apache/Solr/HttpTransport/Interface.php',
	'apache_solr_httptransport_response' => $extensionPath . 'lib/SolrPhpClient/Apache/Solr/HttpTransport/Response.php',
	'apache_solr_service_balancer' => $extensionPath . 'lib/SolrPhpClient/Apache/Solr/Service/Balancer.php',
	'apache_solr_document' => $extensionPath . 'lib/SolrPhpClient/Apache/Solr/Document.php',
	'apache_solr_exception' => $extensionPath . 'lib/SolrPhpClient/Apache/Solr/Exception.php',
	'apache_solr_httptransportexception' => $extensionPath . 'lib/SolrPhpClient/Apache/Solr/HttpTransportException.php',
	'apache_solr_invalidargumentexception' => $extensionPath . 'lib/SolrPhpClient/Apache/Solr/InvalidArgumentException.php',
	'apache_solr_noserviceavailableexception' => $extensionPath . 'lib/SolrPhpClient/Apache/Solr/NoServiceAvailableException.php',
	'apache_solr_parserexception' => $extensionPath . 'lib/SolrPhpClient/Apache/Solr/ParserException.php',
	'apache_solr_response' => $extensionPath . 'lib/SolrPhpClient/Apache/Solr/Response.php',
	'apache_solr_service' => $extensionPath . 'lib/SolrPhpClient/Apache/Solr/Service.php',

		// EXT:solr

	'tx_solr_api' => $extensionPath . 'classes/class.tx_solr_api.php',
	'tx_solr_additionalfieldsindexer' => $extensionPath . 'classes/class.tx_solr_additionalfieldsindexer.php',
	'tx_solr_commandresolver' => $extensionPath . 'classes/class.tx_solr_commandresolver.php',
	'tx_solr_connectionmanager' => $extensionPath . 'classes/class.tx_solr_connectionmanager.php',
	'tx_solr_contextmenuactioncontroller' => $extensionPath . 'classes/class.tx_solr_contextmenuactioncontroller.php',
	'tx_solr_garbagecollector' => $extensionPath . 'classes/class.tx_solr_garbagecollector.php',
	'tx_solr_htmlcontentextractor' => $extensionPath . 'classes/class.tx_solr_htmlcontentextractor.php',
	'tx_solr_javascriptmanager' => $extensionPath . 'classes/class.tx_solr_javascriptmanager.php',
	'tx_solr_languagefileunavailableexception' => $extensionPath . 'classes/class.tx_solr_languagefileunavailableexception.php',
	'tx_solr_nosolrconnectionfoundexception' => $extensionPath . 'classes/class.tx_solr_nosolrconnectionfoundexception.php',
	'tx_solr_query' => $extensionPath . 'classes/class.tx_solr_query.php',
	'tx_solr_search' => $extensionPath . 'classes/class.tx_solr_search.php',
	'tx_solr_site' => $extensionPath . 'classes/class.tx_solr_site.php',
	'tx_solr_solrservice' => $extensionPath . 'classes/class.tx_solr_solrservice.php',
	'tx_solr_sorting' => $extensionPath . 'classes/class.tx_solr_sorting.php',
	'tx_solr_spellchecker' => $extensionPath . 'classes/class.tx_solr_spellchecker.php',
	'tx_solr_suggestquery' => $extensionPath . 'classes/class.tx_solr_suggestquery.php',
	'tx_solr_template' => $extensionPath . 'classes/class.tx_solr_template.php',
	'tx_solr_typo3environment' => $extensionPath . 'classes/class.tx_solr_typo3environment.php',
	'tx_solr_typo3pagecontentextractor' => $extensionPath . 'classes/class.tx_solr_typo3pagecontentextractor.php',
	'tx_solr_typo3pageindexer' => $extensionPath . 'classes/class.tx_solr_typo3pageindexer.php',
	'tx_solr_util' => $extensionPath . 'classes/class.tx_solr_util.php',

	'tx_solr_access_rootline' => $extensionPath . 'classes/access/class.tx_solr_access_rootline.php',
	'tx_solr_access_rootlineelement' => $extensionPath . 'classes/access/class.tx_solr_access_rootlineelement.php',
	'tx_solr_access_rootlineelementformatexception' => $extensionPath . 'classes/access/class.tx_solr_access_rootlineelementformatexception.php',

	'tx_solr_cli_dispatcher' => $extensionPath . 'classes/cli/class.tx_solr_cli_dispatcher.php',

	'tx_solr_contentobject_content' => $extensionPath . 'classes/contentobject/class.tx_solr_contentobject_content.php',
	'tx_solr_contentobject_multivalue' => $extensionPath . 'classes/contentobject/class.tx_solr_contentobject_multivalue.php',
	'tx_solr_contentobject_relation' => $extensionPath . 'classes/contentobject/class.tx_solr_contentobject_relation.php',

	'tx_solr_facet_abstractfacetrenderer' => $extensionPath . 'classes/facet/class.tx_solr_facet_abstractfacetrenderer.php',
	'tx_solr_facet_daterangefacetrenderer' => $extensionPath . 'classes/facet/class.tx_solr_facet_daterangefacetrenderer.php',
	'tx_solr_facet_facet' => $extensionPath . 'classes/facet/class.tx_solr_facet_facet.php',
	'tx_solr_facet_facetoption' => $extensionPath . 'classes/facet/class.tx_solr_facet_facetoption.php',
	'tx_solr_facet_facetrendererfactory' => $extensionPath . 'classes/facet/class.tx_solr_facet_facetrendererfactory.php',
	'tx_solr_facet_hierarchicalfacetrenderer' => $extensionPath . 'classes/facet/class.tx_solr_facet_hierarchicalfacetrenderer.php',
	'tx_solr_facet_hierarchicalfacethelper' => $extensionPath . 'classes/facet/class.tx_solr_facet_hierarchicalfacethelper.php',
	'tx_solr_facet_linkbuilder' => $extensionPath . 'classes/facet/class.tx_solr_facet_linkbuilder.php',
	'tx_solr_facet_numericrangefacetrenderer' => $extensionPath . 'classes/facet/class.tx_solr_facet_numericrangefacetrenderer.php',
	'tx_solr_facet_querygroupfacetrenderer' => $extensionPath . 'classes/facet/class.tx_solr_facet_querygroupfacetrenderer.php',
	'tx_solr_facet_simplefacetrenderer' => $extensionPath . 'classes/facet/class.tx_solr_facet_simplefacetrenderer.php',
	'tx_solr_facet_simplefacetoptionsrenderer' => $extensionPath . 'classes/facet/class.tx_solr_facet_simplefacetoptionsrenderer.php',
	'tx_solr_facet_usedfacetrenderer' => $extensionPath . 'classes/facet/class.tx_solr_facet_usedfacetrenderer.php',

	'tx_solr_fieldprocessor_pageuidtohierarchy' => $extensionPath . 'classes/fieldprocessor/class.tx_solr_fieldprocessor_pageuidtohierarchy.php',
	'tx_solr_fieldprocessor_pathtohierarchy' => $extensionPath . 'classes/fieldprocessor/class.tx_solr_fieldprocessor_pathtohierarchy.php',
	'tx_solr_fieldprocessor_service' => $extensionPath . 'classes/fieldprocessor/class.tx_solr_fieldprocessor_service.php',
	'tx_solr_fieldprocessor_timestamptoisodate' => $extensionPath . 'classes/fieldprocessor/class.tx_solr_fieldprocessor_timestamptoisodate.php',

	'tx_solr_indexqueue_abstractindexer' => $extensionPath . 'classes/indexqueue/class.tx_solr_indexqueue_abstractindexer.php',
	'tx_solr_indexqueue_indexer' => $extensionPath . 'classes/indexqueue/class.tx_solr_indexqueue_indexer.php',
	'tx_solr_indexqueue_item' => $extensionPath . 'classes/indexqueue/class.tx_solr_indexqueue_item.php',
	'tx_solr_indexqueue_pageindexer' => $extensionPath . 'classes/indexqueue/class.tx_solr_indexqueue_pageindexer.php',
	'tx_solr_indexqueue_pageindexerrequest' => $extensionPath . 'classes/indexqueue/class.tx_solr_indexqueue_pageindexerrequest.php',
	'tx_solr_indexqueue_pageindexerrequesthandler' => $extensionPath . 'classes/indexqueue/class.tx_solr_indexqueue_pageindexerrequesthandler.php',
	'tx_solr_indexqueue_pageindexerresponse' => $extensionPath . 'classes/indexqueue/class.tx_solr_indexqueue_pageindexerresponse.php',
	'tx_solr_indexqueue_queue' => $extensionPath . 'classes/indexqueue/class.tx_solr_indexqueue_queue.php',
	'tx_solr_indexqueue_recordmonitor' => $extensionPath . 'classes/indexqueue/class.tx_solr_indexqueue_recordmonitor.php',

	'tx_solr_indexqueue_frontendhelper_abstract' => $extensionPath . 'classes/indexqueue/frontendhelper/class.tx_solr_indexqueue_frontendhelper_abstract.php',
	'tx_solr_indexqueue_frontendhelper_authorizationservice' => $extensionPath . 'classes/indexqueue/frontendhelper/class.tx_solr_indexqueue_frontendhelper_authorizationservice.php',
	'tx_solr_indexqueue_frontendhelper_dispatcher' => $extensionPath . 'classes/indexqueue/frontendhelper/class.tx_solr_indexqueue_frontendhelper_dispatcher.php',
	'tx_solr_indexqueue_frontendhelper_manager' => $extensionPath . 'classes/indexqueue/frontendhelper/class.tx_solr_indexqueue_frontendhelper_manager.php',
	'tx_solr_indexqueue_frontendhelper_usergroupdetector' => $extensionPath . 'classes/indexqueue/frontendhelper/class.tx_solr_indexqueue_frontendhelper_usergroupdetector.php',
	'tx_solr_indexqueue_frontendhelper_pagefieldmappingindexer' => $extensionPath . 'classes/indexqueue/frontendhelper/class.tx_solr_indexqueue_frontendhelper_pagefieldmappingindexer.php',
	'tx_solr_indexqueue_frontendhelper_pageindexer' => $extensionPath . 'classes/indexqueue/frontendhelper/class.tx_solr_indexqueue_frontendhelper_pageindexer.php',

	'tx_solr_indexqueue_initializer_abstract' => $extensionPath . 'classes/indexqueue/initializer/class.tx_solr_indexqueue_initializer_abstract.php',
	'tx_solr_indexqueue_initializer_page' => $extensionPath . 'classes/indexqueue/initializer/class.tx_solr_indexqueue_initializer_page.php',
	'tx_solr_indexqueue_initializer_record' => $extensionPath . 'classes/indexqueue/initializer/class.tx_solr_indexqueue_initializer_record.php',

	'tx_solr_pluginbase_backendsummary' => $extensionPath . 'classes/pluginbase/class.tx_solr_pluginbase_backendsummary.php',
	'tx_solr_pluginbase_commandpluginbase' => $extensionPath . 'classes/pluginbase/class.tx_solr_pluginbase_commandpluginbase.php',
	'tx_solr_pluginbase_pluginbase' => $extensionPath . 'classes/pluginbase/class.tx_solr_pluginbase_pluginbase.php',

	'tx_solr_query_linkbuilder' => $extensionPath . 'classes/query/class.tx_solr_query_linkbuilder.php',

	'tx_solr_query_filterencoder_daterange' => $extensionPath . 'classes/query/filterencoder/class.tx_solr_query_filterencoder_daterange.php',
	'tx_solr_query_filterencoder_hierarchy' => $extensionPath . 'classes/query/filterencoder/class.tx_solr_query_filterencoder_hierarchy.php',
	'tx_solr_query_filterencoder_querygroup' => $extensionPath . 'classes/query/filterencoder/class.tx_solr_query_filterencoder_querygroup.php',
	'tx_solr_query_filterencoder_range' => $extensionPath . 'classes/query/filterencoder/class.tx_solr_query_filterencoder_range.php',

	'tx_solr_query_modifier_faceting' => $extensionPath . 'classes/query/modifier/class.tx_solr_query_modifier_faceting.php',
	'tx_solr_query_modifier_statistics' => $extensionPath . 'classes/query/modifier/class.tx_solr_query_modifier_statistics.php',

	'tx_solr_response_processor_statisticswriter' => $extensionPath . 'classes/response/processor/class.tx_solr_response_processor_statisticswriter.php',

	'tx_solr_resultdocumentmodifier_scoreanalyzer' => $extensionPath . 'classes/resultdocumentmodifier/class.tx_solr_resultdocumentmodifier_scoreanalyzer.php',
	'tx_solr_resultdocumentmodifier_sitehighlighter' => $extensionPath . 'classes/resultdocumentmodifier/class.tx_solr_resultdocumentmodifier_sitehighlighter.php',

	'tx_solr_resultsetmodifier_lastsearches' => $extensionPath . 'classes/resultsetmodifier/class.tx_solr_resultsetmodifier_lastsearches.php',

	'tx_solr_search_abstractcomponent' => $extensionPath . 'classes/search/class.tx_solr_search_abstractcomponent.php',
	'tx_solr_search_accesscomponent' => $extensionPath . 'classes/search/class.tx_solr_search_accesscomponent.php',
	'tx_solr_search_analysiscomponent' => $extensionPath . 'classes/search/class.tx_solr_search_analysiscomponent.php',
	'tx_solr_search_debugcomponent' => $extensionPath . 'classes/search/class.tx_solr_search_debugcomponent.php',
	'tx_solr_search_facetingcomponent' => $extensionPath . 'classes/search/class.tx_solr_search_facetingcomponent.php',
	'tx_solr_search_highlightingcomponent' => $extensionPath . 'classes/search/class.tx_solr_search_highlightingcomponent.php',
	'tx_solr_search_lastsearchescomponent' => $extensionPath . 'classes/search/class.tx_solr_search_lastsearchescomponent.php',
	'tx_solr_search_relevancecomponent' => $extensionPath . 'classes/search/class.tx_solr_search_relevancecomponent.php',
	'tx_solr_search_searchcomponentmanager' => $extensionPath . 'classes/search/class.tx_solr_search_searchcomponentmanager.php',
	'tx_solr_search_sortingcomponent' => $extensionPath . 'classes/search/class.tx_solr_search_sortingcomponent.php',
	'tx_solr_search_spellcheckingcomponent' => $extensionPath . 'classes/search/class.tx_solr_search_spellcheckingcomponent.php',
	'tx_solr_search_statisticscomponent' => $extensionPath . 'classes/search/class.tx_solr_search_statisticscomponent.php',

	'tx_solr_viewhelper_abstractsubpartviewhelper' => $extensionPath . 'classes/viewhelper/class.tx_solr_viewhelper_abstractsubpartviewhelper.php',
	'tx_solr_viewhelper_crop' => $extensionPath . 'classes/viewhelper/class.tx_solr_viewhelper_crop.php',
	'tx_solr_viewhelper_currentresultnumber' => $extensionPath . 'classes/viewhelper/class.tx_solr_viewhelper_currentresultnumber.php',
	'tx_solr_viewhelper_date' => $extensionPath . 'classes/viewhelper/class.tx_solr_viewhelper_date.php',
	'tx_solr_viewhelper_facet' => $extensionPath . 'classes/viewhelper/class.tx_solr_viewhelper_facet.php',
	'tx_solr_viewhelper_link' => $extensionPath . 'classes/viewhelper/class.tx_solr_viewhelper_link.php',
	'tx_solr_viewhelper_lll' => $extensionPath . 'classes/viewhelper/class.tx_solr_viewhelper_lll.php',
	'tx_solr_viewhelper_multivalue' => $extensionPath . 'classes/viewhelper/class.tx_solr_viewhelper_multivalue.php',
	'tx_solr_viewhelper_oddeven' => $extensionPath . 'classes/viewhelper/class.tx_solr_viewhelper_oddeven.php',
	'tx_solr_viewhelper_relevance' => $extensionPath . 'classes/viewhelper/class.tx_solr_viewhelper_relevance.php',
	'tx_solr_viewhelper_relevancebar' => $extensionPath . 'classes/viewhelper/class.tx_solr_viewhelper_relevancebar.php',
	'tx_solr_viewhelper_solrlink' => $extensionPath . 'classes/viewhelper/class.tx_solr_viewhelper_solrlink.php',
	'tx_solr_viewhelper_sortindicator' => $extensionPath . 'classes/viewhelper/class.tx_solr_viewhelper_sortindicator.php',
	'tx_solr_viewhelper_sorturl' => $extensionPath . 'classes/viewhelper/class.tx_solr_viewhelper_sorturl.php',
	'tx_solr_viewhelper_ts' => $extensionPath . 'classes/viewhelper/class.tx_solr_viewhelper_ts.php',

		// modules

	'tx_solr_moduleadmin' => $extensionPath . 'mod_admin/index.php',

	'tx_solr_mod_index_indexinspector' => $extensionPath . 'mod_index/class.tx_solr_mod_index_indexinspector.php',
	'tx_solr_mod_index_indexinspectorremotecontroller' => $extensionPath . 'mod_index/class.tx_solr_mod_index_indexinspectorremotecontroller.php',

		// plugins

	'tx_solr_pi_frequentsearches' => $extensionPath . 'pi_frequentsearches/class.tx_solr_pi_frequentsearches.php',
	'tx_solr_pi_results' => $extensionPath . 'pi_results/class.tx_solr_pi_results.php',
	'tx_solr_pi_search' => $extensionPath . 'pi_search/class.tx_solr_pi_search.php',

	'tx_solr_pi_results_advancedformcommand' => $extensionPath . 'pi_results/class.tx_solr_pi_results_advancedformcommand.php',
	'tx_solr_pi_results_errorscommand' => $extensionPath . 'pi_results/class.tx_solr_pi_results_errorscommand.php',
	'tx_solr_pi_results_facetingcommand' => $extensionPath . 'pi_results/class.tx_solr_pi_results_facetingcommand.php',
	'tx_solr_pi_results_formcommand' => $extensionPath . 'pi_results/class.tx_solr_pi_results_formcommand.php',
	'tx_solr_pi_results_frequentsearchescommand' => $extensionPath . 'pi_results/class.tx_solr_pi_results_frequentsearchescommand.php',
	'tx_solr_pi_results_highlightingresultdocumentmodifier' => $extensionPath . 'pi_results/class.tx_solr_pi_results_highlightingresultdocumentmodifier.php',
	'tx_solr_pi_results_lastsearchescommand' => $extensionPath . 'pi_results/class.tx_solr_pi_results_lastsearchescommand.php',
	'tx_solr_pi_results_noresultscommand' => $extensionPath . 'pi_results/class.tx_solr_pi_results_noresultscommand.php',
	'tx_solr_pi_results_resultscommand' => $extensionPath . 'pi_results/class.tx_solr_pi_results_resultscommand.php',
	'tx_solr_pi_results_resultsperpageswitchcommand' => $extensionPath . 'pi_results/class.tx_solr_pi_results_resultsperpageswitchcommand.php',
	'tx_solr_pi_results_sortingcommand' => $extensionPath . 'pi_results/class.tx_solr_pi_results_sortingcommand.php',

	'tx_solr_pi_results_parameterkeepingformmodifier' => $extensionPath . 'pi_results/class.tx_solr_pi_results_parameterkeepingformmodifier.php',
	'tx_solr_pi_results_spellcheckformmodifier' => $extensionPath . 'pi_results/class.tx_solr_pi_results_spellcheckformmodifier.php',
	'tx_solr_pi_results_suggestformmodifier' => $extensionPath . 'pi_results/class.tx_solr_pi_results_suggestformmodifier.php',

		// scheduler tasks

	'tx_solr_scheduler_committask' => $extensionPath . 'scheduler/class.tx_solr_scheduler_committask.php',
	'tx_solr_scheduler_committasksolrserverfield' => $extensionPath . 'scheduler/class.tx_solr_scheduler_committasksolrserverfield.php',
	'tx_solr_scheduler_indexqueueworkertask' => $extensionPath . 'scheduler/class.tx_solr_scheduler_indexqueueworkertask.php',
	'tx_solr_scheduler_indexqueueworkertaskadditionalfieldprovider' => $extensionPath . 'scheduler/class.tx_solr_scheduler_indexqueueworkertaskadditionalfieldprovider.php',
	'tx_solr_scheduler_optimizetask' => $extensionPath . 'scheduler/class.tx_solr_scheduler_optimizetask.php',
	'tx_solr_scheduler_optimizetasksolrserverfield' => $extensionPath . 'scheduler/class.tx_solr_scheduler_optimizetasksolrserverfield.php',
	'tx_solr_scheduler_reindextask' => $extensionPath . 'scheduler/class.tx_solr_scheduler_reindextask.php',
	'tx_solr_scheduler_reindextasksolrserverfield' => $extensionPath . 'scheduler/class.tx_solr_scheduler_reindextasksolrserverfield.php',

		// reports

	'tx_solr_report_accessfilterplugininstalledstatus' => $extensionPath . 'report/class.tx_solr_report_accessfilterplugininstalledstatus.php',
	'tx_solr_report_allowurlfopenstatus' => $extensionPath . 'report/class.tx_solr_report_allowurlfopenstatus.php',
	'tx_solr_report_filtervarstatus' => $extensionPath . 'report/class.tx_solr_report_filtervarstatus.php',
	'tx_solr_report_indexreport' => $extensionPath . 'report/class.tx_solr_report_indexreport.php',
	'tx_solr_report_schemastatus' => $extensionPath . 'report/class.tx_solr_report_schemastatus.php',
	'tx_solr_report_solrconfigstatus' => $extensionPath . 'report/class.tx_solr_report_solrconfigstatus.php',
	'tx_solr_report_solrconfigurationstatus' => $extensionPath . 'report/class.tx_solr_report_solrconfigurationstatus.php',
	'tx_solr_report_solrstatus' => $extensionPath . 'report/class.tx_solr_report_solrstatus.php',
	'tx_solr_report_solrversionstatus' => $extensionPath . 'report/class.tx_solr_report_solrversionstatus.php',
	'tx_solr_report_statisticsreport' => $extensionPath . 'report/class.tx_solr_report_statisticsreport.php',

		// interfaces

	'tx_solr_additionalindexqueueitemindexer' => $extensionPath . 'interfaces/interface.tx_solr_additionalindexqueueitemindexer.php',
	'tx_solr_additionalpageindexer' => $extensionPath . 'interfaces/interface.tx_solr_additionalpageindexer.php',
	'tx_solr_commandpluginaware' => $extensionPath . 'interfaces/interface.tx_solr_commandpluginaware.php',
	'tx_solr_commandpostprocessor' => $extensionPath . 'interfaces/interface.tx_solr_commandpostprocessor.php',
	'tx_solr_facetoptionsrenderer' => $extensionPath . 'interfaces/interface.tx_solr_facetoptionsrenderer.php',
	'tx_solr_facetrenderer' => $extensionPath . 'interfaces/interface.tx_solr_facetrenderer.php',
	'tx_solr_facetsmodifier' =>  $extensionPath . 'interfaces/interface.tx_solr_facetsmodifier.php',
	'tx_solr_fieldprocessor' => $extensionPath . 'interfaces/interface.tx_solr_fieldprocessor.php',
	'tx_solr_formmodifier' => $extensionPath . 'interfaces/interface.tx_solr_formmodifier.php',
	'tx_solr_garbagecollectorpostprocessor' => $extensionPath . 'interfaces/interface.tx_solr_garbagecollectorpostprocessor.php',
	'tx_solr_indexqueueinitializationpostprocessor' => $extensionPath . 'interfaces/interface.tx_solr_indexqueueinitializationpostprocessor.php',
	'tx_solr_indexqueueinitializer' => $extensionPath . 'interfaces/interface.tx_solr_indexqueueinitializer.php',
	'tx_solr_indexqueuepageindexerdataurlmodifier' => $extensionPath . 'interfaces/interface.tx_solr_indexqueuepageindexerdataurlmodifier.php',
	'tx_solr_indexqueuepageindexerdocumentsmodifier' => $extensionPath . 'interfaces/interface.tx_solr_indexqueuepageindexerdocumentsmodifier.php',
	'tx_solr_indexqueuepageindexerfrontendhelper' => $extensionPath . 'interfaces/interface.tx_solr_indexqueuepageindexerfrontendhelper.php',
	'tx_solr_plugincommand' => $extensionPath . 'interfaces/interface.tx_solr_plugincommand.php',
	'tx_solr_pluginaware' => $extensionPath . 'interfaces/interface.tx_solr_pluginaware.php',
	'tx_solr_queryaware' => $extensionPath . 'interfaces/interface.tx_solr_queryaware.php',
	'tx_solr_queryfacetbuilder' => $extensionPath . 'interfaces/interface.tx_solr_queryfacetbuilder.php',
	'tx_solr_queryfilterencoder' => $extensionPath . 'interfaces/interface.tx_solr_queryfilterencoder.php',
	'tx_solr_querymodifier' => $extensionPath . 'interfaces/interface.tx_solr_querymodifier.php',
	'tx_solr_responsemodifier' => $extensionPath . 'interfaces/interface.tx_solr_responsemodifier.php',
	'tx_solr_responseprocessor' => $extensionPath . 'interfaces/interface.tx_solr_responseprocessor.php',
	'tx_solr_resultdocumentmodifier' => $extensionPath . 'interfaces/interface.tx_solr_resultdocumentmodifier.php',
	'tx_solr_resultsetmodifier' => $extensionPath . 'interfaces/interface.tx_solr_resultsetmodifier.php',
	'tx_solr_searchaware' => $extensionPath . 'interfaces/interface.tx_solr_searchaware.php',
	'tx_solr_searchcomponent' => $extensionPath . 'interfaces/interface.tx_solr_searchcomponent.php',
	'tx_solr_subpartviewhelper' => $extensionPath . 'interfaces/interface.tx_solr_subpartviewhelper.php',
	'tx_solr_substitutepageindexer' => $extensionPath . 'interfaces/interface.tx_solr_substitutepageindexer.php',
	'tx_solr_templatemodifier' => $extensionPath . 'interfaces/interface.tx_solr_templatemodifier.php',
	'tx_solr_viewhelper' => $extensionPath . 'interfaces/interface.tx_solr_viewhelper.php',
	'tx_solr_viewhelperprovider' => $extensionPath . 'interfaces/interface.tx_solr_viewhelperprovider.php',
);
?>