#!/bin/bash
### BEGIN INIT INFO
# Provides:     tomcat6
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Tomcat Server
# Description: Tomcat Server basic start/shutdown script
# processname: tomcat
### END INIT INFO


setJdk() {
    JDK_DIRS="/usr/lib/jvm/java-7-openjdk /usr/lib/jvm/java-7-openjdk-i386 /usr/lib/jvm/java-7-openjdk-amd64"
    for jdir in $JDK_DIRS; do
        if [ -r "$jdir/bin/java" ]; then
            JAVA_HOME="$jdir"
            echo "JAVA_HOME has been automatically set to $JAVA_HOME"
            break
        fi
    done

    if [[ ! "$JAVA_HOME" = *"java-7"* ]]; then
        echo "JAVA_HOME could not be set to Java 7. Please define JAVA_HOME manually."
        exit 1
    fi
}

if [ ! -z "$JAVA_HOME" ] && [[ ! "$JAVA_HOME" = *"java-7"* ]]; then
    echo "JAVA_HOME is not set to Java 7. Searching now for JDK installation in default places..."
    setJdk
elif [ -z "$JAVA_HOME" ]; then
    echo "JAVA_HOME has not been set. Searching now for JDK installation in default places..."
    setJdk
fi


#JAVA_OPTS="$JAVA_OPTS -Dsolr.solr.home=/opt/solr-tomcat/solr"
export JAVA_HOME
#export JAVA_OPTS

TOMCAT_HOME=/opt/solr-tomcat/tomcat/bin
START_TOMCAT=/opt/solr-tomcat/tomcat/bin/startup.sh
STOP_TOMCAT=/opt/solr-tomcat/tomcat/bin/shutdown.sh

start() {
echo -n "Starting tomcat: "
cd $TOMCAT_HOME
${START_TOMCAT}
echo "done."
}

stop() {
echo -n "Shutting down tomcat: "
cd $TOMCAT_HOME
${STOP_TOMCAT}
echo "done."
}

case "$1" in
start)
start
;;
stop)
stop
;;
restart)
stop
sleep 10
start
;;
*)
echo "Usage: $0 {start|stop|restart}"
esac
exit 0