#!/bin/bash
#
# tomcat
#
# chkconfig: 2345 95 05
# description: 	Start up the Tomcat servlet engine.

### BEGIN INIT INFO
# Provides:     tomcat6
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Tomcat Server
# Description: Tomcat Server basic start/shutdown script
# processname: tomcat
### END INIT INFO

RETVAL=$?
CATALINA_HOME="/opt/solr-tomcat/tomcat"

setJdk() {
    JDK_DIRS="/usr/lib/jvm/java-7-openjdk /usr/lib/jvm/java-7-openjdk-i386 /usr/lib/jvm/java-7-openjdk-amd64"
    for jdir in $JDK_DIRS; do
        if [ -r "$jdir/bin/java" ]; then
            JAVA_HOME="$jdir"
            echo "JAVA_HOME has been automatically set to $JAVA_HOME"
            break
        fi
    done

    if [[ ! "$JAVA_HOME" = *"java-7"* ]]; then
        echo "JAVA_HOME could not be set to Java 7. Please define JAVA_HOME manually."
        exit 1
    fi
}

if [ ! -z "$JAVA_HOME" ] && [[ ! "$JAVA_HOME" = *"java-7"* ]]; then
    echo "JAVA_HOME is not set to Java 7. Searching now for JDK installation in default places..."
    setJdk
elif [ -z "$JAVA_HOME" ]; then
    echo "JAVA_HOME has not been set. Searching now for JDK installation in default places..."
    setJdk
fi

export JAVA_HOME

start() {
  if [ -f $CATALINA_HOME/bin/startup.sh ];
    then
      echo $"Starting Tomcat"
      /bin/su tomcat $CATALINA_HOME/bin/startup.sh
      echo "done."
  fi
}

stop() {
  if [ -f $CATALINA_HOME/bin/shutdown.sh ];
    then
      echo $"Stopping Tomcat"
      /bin/su tomcat $CATALINA_HOME/bin/shutdown.sh
      echo "done."
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    sleep 10
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $RETVAL