#!/bin/bash
### BEGIN INIT INFO
# Provides:     tomcat6
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Tomcat Server
# Description: Tomcat Server basic start/shutdown script
# processname: tomcat
### END INIT INFO

JAVA_HOME=/usr/lib/jvm/java-6-openjdk
#JAVA_OPTS="$JAVA_OPTS -Dsolr.solr.home=/opt/solr-tomcat/solr"
export JAVA_HOME
#export JAVA_OPTS

TOMCAT_HOME=/opt/solr-tomcat/tomcat/bin
START_TOMCAT=/opt/solr-tomcat/tomcat/bin/startup.sh
STOP_TOMCAT=/opt/solr-tomcat/tomcat/bin/shutdown.sh

start() {
echo -n "Starting tomcat: "
cd $TOMCAT_HOME
${START_TOMCAT}
echo "done."
}

stop() {
echo -n "Shutting down tomcat: "
cd $TOMCAT_HOME
${STOP_TOMCAT}
echo "done."
}

case "$1" in
start)
start
;;
stop)
stop
;;
restart)
stop
sleep 10
start
;;
*)
echo "Usage: $0 {start|stop|restart}"
esac
exit 0