#!/bin/bash
# chkconfig: 234 20 80
# description: Tomcat Server basic start/shutdown script
# processname: tomcat

JAVA_HOME=/usr/lib/jvm/java-6-sun
#JAVA_OPTS="$JAVA_OPTS -Dsolr.solr.home=/opt/solr-tomcat/solr"
export JAVA_HOME
#export JAVA_OPTS

TOMCAT_HOME=/opt/solr-tomcat/apache-tomcat-6.0.20/bin
START_TOMCAT=/opt/solr-tomcat/apache-tomcat-6.0.20/bin/startup.sh
STOP_TOMCAT=/opt/solr-tomcat/apache-tomcat-6.0.20/bin/shutdown.sh

start() {
echo -n "Starting tomcat: "
cd $TOMCAT_HOME
${START_TOMCAT}
echo "done."
}

stop() {
echo -n "Shutting down tomcat: "
cd $TOMCAT_HOME
${STOP_TOMCAT}
echo "done."
}

case "$1" in
start)
start
;;
stop)
stop
;;
restart)
stop
sleep 10
start
;;
*)
echo "Usage: $0 {start|stop|restart}"
esac
exit 0