<?php

declare(strict_types=1);

/*
 * This file is part of the TYPO3 CMS project.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 *
 * The TYPO3 project - inspiring people to share!
 */

namespace ApacheSolrForTypo3\Solr\ViewHelpers\Backend\Security;

use ApacheSolrForTypo3\Solr\Exception\InvalidArgumentException;
use RuntimeException;
use TYPO3\CMS\Backend\Module\ModuleProvider;
use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3Fluid\Fluid\Core\Rendering\RenderingContextInterface;
use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractConditionViewHelper;

/**
 * This view helper implements an ifHasAccessToModule/else condition for BE users/groups.
 *
 * Class IfHasAccessToModuleViewHelper
 */
class IfHasAccessToModuleViewHelper extends AbstractConditionViewHelper
{
    /**
     * Message for that case, if $arguments['signature'] was used and module does not exist
     */
    public const ERROR_APPENDIX_FOR_WRONG_SIGNATURE_ARGUMENT = 'Please check spelling and style by setting signature="mainName_ExtKeySubmoduleName".';

    /**
     * Message for that case, if $arguments['extension'], $arguments['main'] and $arguments['sub'] are used and module couldn't be resolved
     */
    public const ERROR_APPENDIX_FOR_SIGNATURE_RESOLUTION = 'It was generated by setting extension="%s", main="%s", sub="%s", please check spelling and style by setting this arguments.';

    public function __construct(
        protected readonly ModuleProvider $moduleProvider,
    ) {}

    /**
     * Initializes following arguments: extension, main, sub, signature
     * Renders <f:then> child if the current logged in BE user belongs to the specified role (aka usergroup)
     * otherwise renders <f:else> child.
     */
    public function initializeArguments(): void
    {
        parent::initializeArguments();
        $this->registerArgument('extension', 'string', 'The extension key.');
        $this->registerArgument('main', 'string', 'The main module name.');
        $this->registerArgument('sub', 'string', 'The sub module name.');
        $this->registerArgument('signature', 'string', 'The full signature of module. Simply mainmodulename_submodulename in most cases.');
    }

    /**
     * Store ModuleProvider in ViewHelperVariableContainer before rendering
     * so it can be accessed from the static verdict() method.
     */
    public function render(): mixed
    {
        $this->renderingContext->getViewHelperVariableContainer()->addOrUpdate(
            self::class,
            'moduleProvider',
            $this->moduleProvider,
        );
        return parent::render();
    }

    /**
     * @throws InvalidArgumentException
     */
    public static function verdict(array $arguments, RenderingContextInterface $renderingContext): bool
    {
        // Validate arguments: either signature or all three (extension, main, sub) must be set
        if (empty($arguments['signature'])
            && (
                empty($arguments['extension']) || empty($arguments['main']) || empty($arguments['sub'])
            )
        ) {
            throw new InvalidArgumentException('ifHasAccessToModule view helper requires either "signature" or all three other arguments: "extension", "main" and "sub". Please set arguments properly.', 1496314352);
        }

        /** @var ModuleProvider $moduleProvider */
        $moduleProvider = $renderingContext->getViewHelperVariableContainer()->get(self::class, 'moduleProvider');

        try {
            $hasAccessToModule = $moduleProvider->accessGranted(
                self::getModuleSignatureFromArguments($arguments, $moduleProvider),
                $GLOBALS['BE_USER'],
            );
        } catch (RuntimeException) {
            return false;
        }

        return $hasAccessToModule;
    }

    /**
     * Resolves the module signature from arguments
     */
    protected static function getModuleSignatureFromArguments(array $arguments, ModuleProvider $moduleProvider): string
    {
        $moduleSignature = $arguments['signature'];

        $possibleErrorMessageAppendix = self::ERROR_APPENDIX_FOR_WRONG_SIGNATURE_ARGUMENT;
        $possibleErrorCode = 1496311009;
        if (!is_string($moduleSignature)) {
            $moduleSignature = $arguments['main'];
            $subModuleName = GeneralUtility::underscoredToUpperCamelCase($arguments['sub']);
            $moduleSignature .= '_' . $subModuleName;
            $possibleErrorMessageAppendix = vsprintf(self::ERROR_APPENDIX_FOR_SIGNATURE_RESOLUTION, [$arguments['extension'], $arguments['main'], $arguments['sub']]);
            $possibleErrorCode = 1496311010;
        }

        $moduleSignature = strtolower($moduleSignature);

        if (!$moduleProvider->isModuleRegistered($moduleSignature)) {
            throw new RuntimeException(vsprintf('Module with signature "%s" is not configured or couldn\'t be resolved. ' . $possibleErrorMessageAppendix, [$moduleSignature]), $possibleErrorCode);
        }

        return $moduleSignature;
    }
}
