name: build

on:
  push:
    branches: [ release-11.6.x ]
    tags:
      - "**"
  pull_request:
    branches: [ release-11.6.x ]

env:
  CI_BUILD_DIRECTORY: '/home/runner/work/ext-solr/ext-solr/.Build'
  LOCAL_IMAGE_NAME: 'solrci-image:latest'
  LOCAL_CONTAINER_NAME: 'solrci-container'
  TESTING_SOLR_PORT: 8983
  LOCAL_VOLUME_NAME: 'solrci-volume'
  LOCAL_VOLUME_PATH: '/home/runner/work/ext-solr/ext-solr/.Build/data-solr'
  COMPOSER_NO_AUDIT: 1
  COMPOSER_NO_BLOCKING: 1

jobs:
  ci_bootstrapping:
    name: "Build and test docker image + Collect build matrix"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.collect_build_matrix.outputs.matrix }}
    steps:
      # Workaround for issue with actions/checkout "wrong PR commit checkout":
      #   See:
      #   ** https://github.com/actions/checkout/issues/299#issuecomment-677674415
      #   ** https://github.com/actions/checkout/issues/1359#issuecomment-1631503791
      -
        name: Checkout current state of Pull Request
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      -
        name: Checkout current state of Branch
        if: github.event_name == 'push'
        uses: actions/checkout@v7
      # End: Workaround for issue with actions/checkout...
      -
        name: "Resolve target branch of pull request."
        if: github.event_name == 'pull_request'
        run: |
          echo "BRANCH_NAME=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
      -
        name: "Resolve branch name on push in branch of repository."
        if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')
        run: |
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      -
        # We want to pass tests before the tag/release can be pushed to TER.
        # This step resolves the branch name of the tag to use, to be able to collect proper build matrix values.
        name: "Resolve branch name on release/tag in branch of repository."
        if: startsWith(github.ref, 'refs/tags/')
        # //[!0-9]/ in script below removes possible "v" prefix from major part,
        #   to prevent errors or make it possible to create tags with "v" or other prefixes.
        run: |
          export RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}
          export MAJOR_MINOR_VERSIONS_STRING=$(v=( ${RELEASE_VERSION//./ } ) && echo "${v[0]//[!0-9]/}.${v[1]}")
          export BRANCH_NAME=release-"$MAJOR_MINOR_VERSIONS_STRING".x
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
      -
        name: Collect build matrix
        id: collect_build_matrix
        run: |
          export matrix=$(cat .github/workflows/ci-matrix.json | jq --raw-output .\"${{ env.BRANCH_NAME }}\")
          echo "Base ref is $GITHUB_BASE_REF"
          echo "BRANCH_NAME="$BRANCH_NAME
          echo -e "matrix : "
          echo $matrix
          echo "matrix=$(echo $matrix)" >> $GITHUB_OUTPUT
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      -
        name: Build Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Docker/SolrServer/Dockerfile
          tags: solrci-image:latest
          outputs: type=docker,dest=/tmp/solrci-image.tar
      -
        name: Test Image
        run: |
          pwd
          ls -la ../
          docker load --input /tmp/solrci-image.tar
          docker image ls -a
          ./Build/Test/cibuild_docker.sh
      -
        name: Upload Docker Image
        uses: actions/upload-artifact@v7
        with:
          name: solrci-image
          path: /tmp/solrci-image.tar
      -
        name: Upload Solr-Server containers logs
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: solrci-logs
          path: /tmp/docker_image_logs_**/

  tests:
    runs-on: ubuntu-latest
    needs: ci_bootstrapping
    continue-on-error: ${{ contains(matrix.TYPO3, '-dev') }}
    strategy:
      matrix: ${{ fromJson(needs.ci_bootstrapping.outputs.matrix) }}
    env:
      TYPO3_DATABASE_NAME: 'typo3_ci'
      TYPO3_DATABASE_HOST: '127.0.0.1'
      TYPO3_DATABASE_USERNAME: 'root'
      TYPO3_DATABASE_PASSWORD: 'root'
      TYPO3_VERSION: ${{ matrix.TYPO3 }}

    name: TYPO3 ${{ matrix.TYPO3 }} on PHP ${{ matrix.PHP }}
    steps:
      # Workaround for issue with actions/checkout "wrong PR commit checkout". See: ci_bootstrapping job
      -
        name: Checkout current state of Pull Request
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v7
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.sha }}
      -
        name: Checkout current state of Branch
        if: github.event_name == 'push'
        uses: actions/checkout@v7
        with:
          fetch-depth: 2
      # End: Workaround for issue with actions/checkout...
      -
        name: Mount RAMFS
        run: |
          mkdir -p ${{ env.CI_BUILD_DIRECTORY }}
          sudo mount -t tmpfs -o size=1G none ${{ env.CI_BUILD_DIRECTORY }}
          sudo mkdir -p ${{ env.CI_BUILD_DIRECTORY }}/data-{solr,mysql} \
            && sudo chown $USER ${{ env.CI_BUILD_DIRECTORY }}/data-mysql \
            && sudo chown 8983:8983 ${{ env.CI_BUILD_DIRECTORY }}/data-solr
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      -
        name: Download solrci-image from "ci_bootstrapping" job
        uses: actions/download-artifact@v8
        with:
          name: solrci-image
          path: /tmp
      -
        name: 'Start Docker: Solr, MySQL'
        run: |
          docker load --input /tmp/solrci-image.tar
          docker run --name "MySQL-CI" -v ${{ env.CI_BUILD_DIRECTORY }}/data-mysql:/var/lib/mysql -p 3306:3306 \
            -e MYSQL_DATABASE=$TYPO3_DATABASE_NAME \
            -e MYSQL_ROOT_PASSWORD=$TYPO3_DATABASE_PASSWORD \
            -d mysql:8.0 mysqld --default-authentication-plugin=mysql_native_password
          sudo chmod g+w "$LOCAL_VOLUME_PATH"
          docker volume create --name "$LOCAL_VOLUME_NAME" --opt type=none --opt device="$LOCAL_VOLUME_PATH" --opt o=bind
          docker run --rm --name="$LOCAL_CONTAINER_NAME" -d -p 127.0.0.1:8983:8983 -v "$LOCAL_VOLUME_NAME":"/var/solr" "$LOCAL_IMAGE_NAME"
          docker ps
          rm /tmp/solrci-image.tar
      -
        name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.PHP }}
          coverage: pcov
          tools: composer:2
      -
        name: CI-Bootstrap
        run: |
          ./Build/Test/bootstrap.sh --skip-solr-install
          echo "Current Size of EXT:Solr build Artefacts before run: " \
            && sudo du -sh "${{ env.CI_BUILD_DIRECTORY }}"
      -
        name: CI-Build
        run: |
          ./Build/Test/cibuild.sh
          echo "Current Size of EXT:Solr build Artefacts after run: " \
            && sudo du -sh "${{ env.CI_BUILD_DIRECTORY }}" \
            && sudo du -sh ${{ env.CI_BUILD_DIRECTORY }}/*
      -
        name: Clean up
        run: |
          docker stop "MySQL-CI" 2>&1
          docker stop "$LOCAL_CONTAINER_NAME" 2>&1
          sudo rm -Rf ${{ env.CI_BUILD_DIRECTORY }}/Web/typo3temp/* \
            ${{ env.CI_BUILD_DIRECTORY }}/data-mysql \
            ${{ env.CI_BUILD_DIRECTORY }}/data-solr

  publish-docker-images:
    name: Publish docker-image to registry.dkd.de
    needs: tests
    if: |
      (
        startsWith(github.ref, 'refs/tags/')
      )
    runs-on: ubuntu-latest
    env:
      DOCKER_PLATFORMS:  "linux/amd64"
      DOCKER_REGISTRY_IMAGE_NAME: "registry.dkd.de/dkd/hosted-solr/solr/elts-solr"
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: enrich Environment Variables
        id: env
        run: |
          echo "NOW=$(date +'%F %Z %T')" >> $GITHUB_ENV
          echo "BRANCH_TAG=$(jq -r '.extra."branch-alias" | to_entries | .[0].key' composer.json)" >> $GITHUB_ENV
          echo "BRANCH_ALIAS_TAG=$(jq -r '.extra."branch-alias" | to_entries | .[0].value' composer.json)" >> $GITHUB_ENV

      - name: Docker metadata AMD64
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            ${{ env.DOCKER_REGISTRY_IMAGE_NAME }}

          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=false
          labels: |
            org.opencontainers.image.title=${{github.event.repository.name}}
            org.opencontainers.image.description=Docker image for Apache Solr for TYPO3 CMS EXT:solr extension
            org.opencontainers.image.vendor=${{github.repository_owner}}
            org.opencontainers.image.licenses=GPL-3.0,APACHE
            org.opencontainers.image.version=${{github.ref_name}}
            org.opencontainers.image.created=${{ env.NOW }}
            org.opencontainers.image.source=${{github.server_url}}/${{github.repository}}
            org.opencontainers.image.revision=${{github.sha}}
            org.opencontainers.image.url=https://docs.typo3.org/p/apache-solr-for-typo3/solr/main/en-us/Appendix/DockerTweaks.html
            org.opencontainers.image.documentation=https://docs.typo3.org/p/apache-solr-for-typo3/solr/main/en-us/Index.html

      - name: Docker metadata ARM64
        id: meta-ARM64
        uses: docker/metadata-action@v6
        with:
          images: |
            ${{ env.DOCKER_REGISTRY_IMAGE_NAME }}

          tags: |
            type=semver,pattern=ARM64_{{version}}
            type=semver,pattern=ARM64_{{major}}.{{minor}}
          flavor: |
            latest=false
          labels: |
            org.opencontainers.image.title=${{github.event.repository.name}}
            org.opencontainers.image.description=Docker image for Apache Solr for TYPO3 CMS EXT:solr extension
            org.opencontainers.image.vendor=${{github.repository_owner}}
            org.opencontainers.image.licenses=GPL-3.0,APACHE
            org.opencontainers.image.version=${{github.ref_name}}
            org.opencontainers.image.created=${{ env.NOW }}
            org.opencontainers.image.source=${{github.server_url}}/${{github.repository}}
            org.opencontainers.image.revision=${{github.sha}}
            org.opencontainers.image.url=https://docs.typo3.org/p/apache-solr-for-typo3/solr/main/en-us/Appendix/DockerTweaks.html
            org.opencontainers.image.documentation=https://docs.typo3.org/p/apache-solr-for-typo3/solr/main/en-us/Index.html

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      -
        name: Login to Docker Registry
        uses: docker/login-action@v4
        with:
          registry: registry.dkd.de
          username: ${{ secrets.DKD_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DKD_DOCKER_REGISTRY_TOKEN }}

      -
        name: Build and push AMD64
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Docker/SolrServer/Dockerfile
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push ARM64
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Docker/SolrServer/Dockerfile
          platforms: "linux/arm64"
          push: true
          provenance: false
          tags: ${{ steps.meta-ARM64.outputs.tags }}
          labels: ${{ steps.meta-ARM64.outputs.labels }}

  publish:
    name: Publish on Release as attachment
    needs: tests
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v7
      -
        name: Build EXT as ZIP for TER
        run: |
          TYPO3_VERSION=$STANDARD_TYPO3_VERSION composer ext:build:for-ter

      -
        name: Upload EXT for TER on release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            .Build/archive/solr.zip
